language: php

matrix:
  include:
#    - php: 5.3
#    - php: 5.3.3
#      env: DEPENDENCIES='low'
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: DEPENDENCIES='dev'
    - php: 5.6
    - php: hhvm
    - php: hhvm-nightly
    - php: 7.0
  allow_failures:
    - php: hhvm-nightly
    - php: 7.0
    - env: DEPENDENCIES='dev'
  #fast_finish: true

before_install:
  - sudo apt-get install expect
  - composer selfupdate

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - if [ "$DEPENDENCIES" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [ "$DEPENDENCIES" != "low" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest; fi;

script:
   - bin/phpspec run --format=pretty
   - bin/behat --format=pretty --stop-on-failure
