language: php

addons:
  apt:
    packages:
      - expect

matrix:
  include:
    - php: 7.0
    - php: 5.6
    - php: 5.6
      env: DEPENDENCIES='dev'
    - php: 5.5
    - php: hhvm
    - php: hhvm-nightly
  allow_failures:
    - php: hhvm-nightly
    - env: DEPENDENCIES='dev'
  fast_finish: true

before_install:
  - composer selfupdate

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - if [ "$DEPENDENCIES" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [ "$DEPENDENCIES" != "low" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest; fi;

script:
   - bin/phpspec run --format=pretty
   - bin/behat --format=pretty --stop-on-failure
